# Generated by Django 3.1.1 on 2021-05-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_db_step'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='DB_host',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('host', models.CharField(max_length=100, null=True)),
        #         ('des', models.CharField(max_length=100, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='DB_login',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('project_id', models.CharField(max_length=10, null=True)),
        #         ('api_method', models.CharField(max_length=10, null=True)),
        #         ('api_url', models.CharField(max_length=1000, null=True)),
        #         ('api_host', models.CharField(max_length=100, null=True)),
        #         ('api_header', models.CharField(max_length=1000, null=True)),
        #         ('body_method', models.CharField(max_length=20, null=True)),
        #         ('api_body', models.CharField(max_length=1000, null=True)),
        #         ('sign', models.CharField(max_length=10, null=True)),
        #         ('set', models.CharField(max_length=300, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='DB_project_header',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('project_id', models.CharField(max_length=10, null=True)),
        #         ('name', models.CharField(max_length=20, null=True)),
        #         ('key', models.CharField(max_length=20, null=True)),
        #         ('value', models.TextField(null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='DB_project_host',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('project_id', models.CharField(max_length=10, null=True)),
        #         ('name', models.CharField(max_length=20, null=True)),
        #         ('host', models.TextField(null=True)),
        #     ],
        # ),
        migrations.AddField(
            model_name='db_step',
            name='api_login',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='db_step',
            name='mock_res',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='db_step',
            name='public_header',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
