# Generated by Django 3.1 on 2021-03-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_db_project_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_project_host',
            name='des',
        ),
        migrations.AddField(
            model_name='db_project_host',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='db_project_host',
            name='project_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='db_project_host',
            name='host',
            field=models.TextField(null=True),
        ),
    ]
