# Generated by Django 3.1 on 2021-03-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_auto_20210324_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=10, null=True)),
                ('api_method', models.CharField(max_length=10, null=True)),
                ('api_url', models.CharField(max_length=1000, null=True)),
                ('api_host', models.CharField(max_length=100, null=True)),
                ('api_header', models.CharField(max_length=1000, null=True)),
                ('body_method', models.CharField(max_length=20, null=True)),
                ('api_body', models.CharField(max_length=1000, null=True)),
                ('sign', models.CharField(max_length=10, null=True)),
                ('set', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
